### PR TITLE
V2.2

### PR DESCRIPTION
**Pull request by Champers5000**
Added an RC filter to each of the temperature inputs to help eliminate noise from high voltage lines. 

### Minimum Prerequisites 

- [X] Pushed changes to branch. 

- [x] The board passes ERC and DRC. 

    - Note some ERC warnings are acceptable. 

- [x] All traces are routed. 

- [x] Units are in metric. 

- [x] Everything in schematic level is annotated and all components have datasheets associated with them. 
- [x] BOM was generated at schematic level and mouser cart link in in the BOM 

- Make sure mouser cart link is saved so anyone can open on their machine (you need to create an account) 

- [x] 2 Members of the team have already reviewed my PR 

- NOTE: Approver will not look at PR if 2 other members haven't reviewed first 

- [x] Is proper noise resistance given to all peripheral devices (bypass caps and coils/ferrites)?  
- [x] Is proper ESD protection given to all MCU input pins (zener diodes)?  
- [x] Is proper power protection given to peripheral devices (zener diodes)?  
- [x] Are peripheral units used properly (reading datasheet)? 
- [x] Are testing points added at useful places?  
- [x] Is there proper short to GND protection at MCU outputs (inline resistors)?  
- [x] Do ADC inputs have caps?  
- [x] Are ADC inputs biased so there is room above expected value to determine if value is being overflowed?  
- [x] Are LED's located at useful places (comm, power, debugging, extra GPIO)?  
- [x] Are parts chosen easy to collect?  
- [x] Are parts chosen easy to solder?  
- [x] Is there reverse polarity protection on inputs?  
- [x] Schematic should have version number in Revision portion on bottom right of top level sheet.

### CODE REVIEW

**Comment by HannahSLee14** [comment]
Overall, it's looking good so far! A few comments/questions:

1. I think you meant one of them to be TempSens9?
image
2. This is a bit nit-picky but at least for me, it's hard to tell what the difference between TempSens# and temp# just based on the names. I would either rename them to be something that may be a bit clearer or leave a comment somewhere on the schematic that describes the difference between them. 
3. Both J9 and J14 are named TempConn2. I think one of them was meant to be named TempConn1. 
4. Did we want to have more protection circuitry for the +5V and GND lines? Possibly a TVS diode?
5. Thermistors are resistors that change their resistance depending on the temperature. Therefore, these have at least two terminals, but the connector looks like it assumes there is only one terminal. What is the other terminal of the thermistors going to be connected to?
6. How were we planning on measuring the resistance across the thermistors? (How will the resistance be divided?) I might include an equation to calculate it from this in the comments. 
7. I would label D1 (the green LED) with an informative name like PowerLED or PowerStatus or something like that. 

Great work so far!

**Comment by connorl309** [comment]
This all looks good, I think. I don't know a ton about protection circuitry but it looks like you did the changes that Hannah requested, and I believe the connections are all sane.

**Review by connorl309 — APPROVED** [review]

**Review by tasniabari — APPROVED** [review]
Everything looks fine in the layout, but I'm not sure if routing traces in between the pads of the resistors is ok or not.

**Comment by HannahSLee14** [comment]
Nice job on how neat and organized it is! A few comments: 
- This trace is super close to the GND through hold - I would space it out a little more so it's not pushing JLC's tolerances
image

- Out of curiosity, what's the point of having two ground holes in the center?
- You can put your name somewhere on the board if you want! You spent a lot of time with this so you earned it

**Comment by Champers5000** [comment]
> Nice job on how neat and organized it is! A few comments:
> 
>     * This trace is super close to the GND through hold - I would space it out a little more so it's not pushing JLC's tolerances
>       image
> 
>     * Out of curiosity, what's the point of having two ground holes in the center?
> 
>     * You can put your name somewhere on the board if you want! You spent a lot of time with this so you earned it

The extra ground test points are just for ease in case someone wants to measure the voltage coming into one of the temperature sensors with a multimeter

**Comment by manthanand** [comment]
> > Nice job on how neat and organized it is! A few comments:
> > ```
> > * This trace is super close to the GND through hold - I would space it out a little more so it's not pushing JLC's tolerances
> >   image
> > 
> > * Out of curiosity, what's the point of having two ground holes in the center?
> > 
> > * You can put your name somewhere on the board if you want! You spent a lot of time with this so you earned it
> > ```
> 
> The extra ground test points are just for ease in case someone wants to measure the voltage coming into one of the temperature sensors with a multimeter

Personally feel like the extra ground testpoints are unnecessary since they are going to need to tap the THT connection at the ADC input anyways. Also there are like 5. If you did want to keep them, then just have one.

**Pull request merged**
